package tech.dev.codegen.network.task
import org.gradle.api.tasks.Input
import org.gradle.api.DefaultTask
import org.gradle.api.tasks.TaskAction
import org.gradle.api.tasks.options.Option
import java.io.File
import tech.dev.codegen.network.parser.OpenApiParser
import tech.dev.codegen.network.parser.NetworkSpecMapper
import tech.dev.codegen.network.generator.DtoGenerator
import tech.dev.codegen.network.generator.ApiServiceGenerator
import tech.dev.codegen.network.generator.ApiServiceImplGenerator
import tech.dev.codegen.network.patch.SettingsGradlePatcher

abstract class GenerateNetworkModuleTask : DefaultTask() {

    @get:Input
    @set:Option(option = "service", description = "Target service name (e.g. auth)")
    var serviceName: String = ""

    @get:Input
    @set:Option(option = "spec", description = "URL or Path to OpenAPI/Swagger spec")
    var specLocation: String = ""

    @get:Input
    @set:Option(option = "tag", description = "Filter endpoints by tag")
    var tag: String = ""

    @get:Input
    @set:Option(option = "update-current", description = "Automatically switch alias to new version")
    var updateCurrent: Boolean = false

    @get:Input
    @set:Option(option = "keep", description = "Number of versions to keep before cleanup")
    var keepVersions: String = "5"

    @TaskAction
    fun run() {
        if (serviceName.isBlank()) throw IllegalArgumentException("--service is required")
        if (specLocation.isBlank()) throw IllegalArgumentException("--spec is required")

        println("🚀 Starting Network Module Generation for '$serviceName' from '$specLocation'...")

        val networkDir = File(project.rootDir, "network")
        val serviceDir = File(networkDir, serviceName)
        if (!serviceDir.exists()) serviceDir.mkdirs()

        // 1. Resolve Next Version
        val currentVersions = serviceDir.listFiles { f -> f.isDirectory && f.name.startsWith("v") }
            ?.mapNotNull { it.name.substringAfter("v").toIntOrNull() } ?: emptyList()
        
        val nextVersion = (currentVersions.maxOrNull() ?: 0) + 1
        val moduleName = "v$nextVersion"
        val modulePath = ":network:$serviceName:$moduleName"
        val moduleDir = File(serviceDir, moduleName)
        
        println("📦 Resolving to version v$nextVersion -> Module: $modulePath")

        // 2. Parser/Generator calls
        println("🔍 Parsing Spec...")
        val spec = OpenApiParser.parse(specLocation)
        val endpoints = NetworkSpecMapper.mapEndpoints(spec, tag.takeIf { it.isNotBlank() })

        println("⚙️ Generating module structure...")
        moduleDir.mkdirs()
        File(moduleDir, "build.gradle.kts").writeText(
            """
            plugins {
                id("kmp.dev.library")
                kotlin("plugin.serialization")
            }
            kotlin {
                androidLibrary {
                    namespace = "com.dev.memebattle.network.${serviceName}.v${nextVersion}"
                    compileSdk = libs.versions.compileSdk.get().toInt()
                    minSdk = libs.versions.minSdk.get().toInt()
                }
                listOf(
                    iosArm64(),
                    iosSimulatorArm64()
                ).forEach { iosTarget ->
                    iosTarget.binaries.framework {
                        baseName = "${serviceName.replaceFirstChar { it.uppercase() }}Network"
                        isStatic = true
                    }
                }
                sourceSets {
                    commonMain.dependencies {
                        api(projects.core.network)
                        implementation(libs.ktor.client.core)
                    }
                }
            }
            """.trimIndent()
        )

        // Generate Kotlin code using KotlinPoet
        val pkg = "com.dev.network.${serviceName}.current"
        // In KMP, source code goes to src/commonMain/kotlin
        val srcDir = File(moduleDir, "src/commonMain/kotlin")
        srcDir.mkdirs()
        
        DtoGenerator.generate(moduleDir, pkg, spec.getComponents()?.schemas)
        ApiServiceGenerator.generate(moduleDir, pkg, serviceName, endpoints)
        ApiServiceImplGenerator.generate(moduleDir, pkg, serviceName, endpoints)

        // Move generated files to commonMain (since KotlinPoet uses src/main/kotlin by default or we can just move them)
        val generatedSrcDir = File(moduleDir, "src/main/kotlin")
        if (generatedSrcDir.exists()) {
            generatedSrcDir.copyRecursively(srcDir, true)
            generatedSrcDir.parentFile.deleteRecursively()
        }

        // Remove redundant 'public ' modifiers generated by KotlinPoet
        moduleDir.walkTopDown().filter { it.isFile && it.extension == "kt" }.forEach { file ->
            val cleanContent = file.readText().replace(Regex("(?m)^([ \t]*)public "), "$1")
            file.writeText(cleanContent)
        }

        // 3. Patch Settings
        println("📝 Patching settings.gradle.kts...")
        SettingsGradlePatcher.include(modulePath, project.rootDir)

        // 4. Update Current Alias
        if (updateCurrent) {
            println("🔄 Updating alias module :network:${serviceName}:current to v$nextVersion...")
            val currentDir = File(serviceDir, "current")
            if (!currentDir.exists()) currentDir.mkdirs()
            
            // To fix snake_case to camelCase in accessor
            val accessorName = serviceName.split("_").mapIndexed { i, s -> if (i > 0) s.capitalize() else s }.joinToString("")
            
            File(currentDir, "build.gradle.kts").writeText(
                """
                plugins { id("kmp.dev.library") }
                kotlin {
                    androidLibrary {
                        namespace = "com.dev.memebattle.network.${serviceName}.current"
                        compileSdk = libs.versions.compileSdk.get().toInt()
                        minSdk = libs.versions.minSdk.get().toInt()
                    }
                    listOf(
                        iosArm64(),
                        iosSimulatorArm64()
                    ).forEach { iosTarget ->
                        iosTarget.binaries.framework {
                            baseName = "${serviceName.replaceFirstChar { it.uppercase() }}CurrentNetwork"
                            isStatic = true
                        }
                    }
                    sourceSets {
                        commonMain.dependencies {
                            api(projects.network.${accessorName}.v$nextVersion)
                            implementation(projects.core.network)
                            implementation(libs.koin.core)
                        }
                    }
                }
                """.trimIndent()
            )
            
            val capitalizedService = serviceName.replaceFirstChar { it.uppercase() }
            val diDir = File(currentDir, "src/commonMain/kotlin/com/dev/network/$serviceName/current/di")
            diDir.mkdirs()
            File(diDir, "${capitalizedService}NetworkModule.kt").writeText(
                """
                package com.dev.network.$serviceName.current.di

                import org.koin.dsl.module
                import org.koin.core.qualifier.named
                import com.dev.network.$serviceName.current.api.${capitalizedService}ApiService
                import com.dev.network.$serviceName.current.api.${capitalizedService}ApiServiceImpl

                val ${serviceName}NetworkModule = module {
                    single<${capitalizedService}ApiService> { ${capitalizedService}ApiServiceImpl(get(named("authenticated"))) }
                }
                """.trimIndent()
            )
            
            SettingsGradlePatcher.include(":network:$serviceName:current", project.rootDir)
        }

        // 5. Cleanup
        println("🧹 Running cleanup policy (keep last ${keepVersions})...")
        // CleanupPolicy.apply(serviceName, keepVersions.toInt())

        println("✅ Generation complete! Please sync Gradle.")
    }
}
